# Food Delivery App Data Analysis
In the world of culinary delights and gastronomic adventures, the Zomato dataset project takes center stage. Just as millions of food enthusiasts use the Zomato platform to satisfy their culinary cravings, you step into the role of a data maestro, ready to unlock the secrets hidden within this treasure trove of information.

Your journey in this project begins with a task as vital as preparing the finest ingredients for a gourmet meal—cleaning the dataset. Much like a skilled chef ensuring that every component is pristine and ready for the culinary masterpiece, you meticulously clean and prepare the data. It's about setting the stage for a culinary data symphony.

Once the dataset is impeccably prepped, you delve into the heart of this gastronomic world—the analysis. You become the culinary critic of data, deciphering what makes a restaurant shine, identifying trends in dining preferences, and uncovering the secrets behind customer choices. It's about distilling raw data into flavorful insights.

As the project unfolds, you become the unsung hero behind the scenes. Just like in a bustling kitchen where chefs work tirelessly to create unforgettable dishes, your work enhances the Zomato experience for users and restaurant owners alike. Your insights help restaurants refine their offerings, and diners discover the perfect place to satisfy their cravings.

In this world of data-driven gastronomy, you are the master chef, the data virtuoso, and the storyteller. Your dedication to cleaning, analyzing, and visualizing the Zomato dataset contributes to the magic of discovering new culinary delights and makes every dining experience that much more extraordinary.

**Task 1 Load the library**

In [1]:
# Import the library for data cleaning
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

**Task-2 Zomato's Flavorful Data Universe**

Explore Zomato's dataset for culinary insights. Uncover hidden gems, spot patterns, and inspire innovation. Join us in shaping the future of dining.

In [2]:
# load the dataset and reomve unncessary column like ('address', 'phone')
zomato = pd.read_csv('zomato.csv')
zomato.drop(['address', 'phone'], axis=1, inplace=True)
zomato

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet
...,...,...,...,...,...,...,...,...,...,...,...
56247,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,Whitefield,Bar,NaN,Continental,"1,500",Pubs and bars
56248,Vinod Bar And Restaurant,No,No,NaN,0,Whitefield,Bar,NaN,Finger Food,600,Pubs and bars
56249,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,Whitefield,Bar,NaN,Finger Food,"2,000",Pubs and bars
56250,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars
56251,The Nest - The Den Bengaluru,No,No,3.4 /5,13,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500",Pubs and bars

**Task -3 Refining Zomato's Data Galaxy**

In [3]:
# Rename the three columns ('rate' to 'rating', 'approx_cost(for two people)' to 'approx_cost', 'listed_in(type)' to 'type')
zomato.rename(columns={'rate': 'rating', 'approx_cost(for two people)': 'approx_cost', 'listed_in(type)': 'type'}, inplace=True)
zomato.head(5) # Now see the update data

,name,online_order,book_table,rating,votes,location,rest_type,dish_liked,cuisines,approx_cost,type
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet

**Task-4 Data Crafting**

Our mission with Zomato's data isn't just about managing information; it's about uncovering dining excellence. By refining our data and addressing gaps, we aim to reveal patterns that guide diners and inspire restaurateurs, enriching dining experiences worldwide, one insight at a time.

In [4]:
# Data Cleaning and Handling Null Values.

# Fill null values in the 'online_order' column with 'NA'
zomato['online_order'] = zomato['online_order'].fillna('NA')

# Fill null values in the 'book_table' column with 'NA'
zomato['book_table'] = zomato['book_table'].fillna('NA')

# Replace null values in the 'rating' column with 0
zomato['rating'] = zomato['rating'].fillna(0)

# Replace null values in the 'votes' column with 0
zomato['votes'] = zomato['votes'].fillna(0)

# Fill null values in the 'location' column with 'NA'
zomato['location'] = zomato['location'].fillna('NA')

# Fill null values in the 'rest_type' column with 'NA'
zomato['rest_type'] = zomato['rest_type'].fillna('NA')

# Fill null values in the 'dish_liked' column with 'NA'
zomato['dish_liked'] = zomato['dish_liked'].fillna('NA')

# Fill null values in the 'cuisines' column with 'NA'
zomato['cuisines'] = zomato['cuisines'].fillna('NA')

# Replace null values in the 'approx_cost' column with 0
zomato['approx_cost'] = zomato['approx_cost'].fillna(0)

# Fill null values in the 'type' column with 'NA'
zomato['type'] = zomato['type'].fillna('NA')

# Inspect the data
zomato

,name,online_order,book_table,rating,votes,location,rest_type,dish_liked,cuisines,approx_cost,type
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet
...,...,...,...,...,...,...,...,...,...,...,...
56247,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,Whitefield,Bar,NA,Continental,"1,500",Pubs and bars
56248,Vinod Bar And Restaurant,No,No,0,0,Whitefield,Bar,NA,Finger Food,600,Pubs and bars
56249,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,0,0,Whitefield,Bar,NA,Finger Food,"2,000",Pubs and bars
56250,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars
56251,The Nest - The Den Bengaluru,No,No,3.4 /5,13,"ITPL Main Road, Whitefield","Bar, Casual Dining",NA,"Finger Food, North Indian, Continental","1,500",Pubs and bars

**Task-5 Refining Zomato's Culinary Dataset**

We're purifying the Zomato dataset by removing duplicates. Like astronomers seeking clarity in the night sky, we aim for a clearer understanding of the culinary world. Removing redundancy ensures each restaurant shines uniquely, guiding us to exceptional dining experiences.

In [5]:
#Removing Duplicate Rows.

zomato.drop_duplicates(keep='first', inplace=True)
zomato

,name,online_order,book_table,rating,votes,location,rest_type,dish_liked,cuisines,approx_cost,type
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet
...,...,...,...,...,...,...,...,...,...,...,...
56247,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,Whitefield,Bar,NA,Continental,"1,500",Pubs and bars
56248,Vinod Bar And Restaurant,No,No,0,0,Whitefield,Bar,NA,Finger Food,600,Pubs and bars
56249,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,0,0,Whitefield,Bar,NA,Finger Food,"2,000",Pubs and bars
56250,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars
56251,The Nest - The Den Bengaluru,No,No,3.4 /5,13,"ITPL Main Road, Whitefield","Bar, Casual Dining",NA,"Finger Food, North Indian, Continental","1,500",Pubs and bars

**Task-6 Refining Zomato's Data**
We're focused on eliminating 'RATED' or 'Rated' from our dataset to uncover the authentic essence of dining experiences. This process reveals the true gems of the culinary world..

In [6]:
# Filtering Out Rows Containing 'RATED' or 'Rated' in Specific Columns.

columns_to_check = ['name', 'type', 'approx_cost', 'cuisines', 'dish_liked', 'rest_type', 'location', 'votes', 'rating', 'book_table']

for column in columns_to_check:
    zomato = zomato[zomato[column].str.contains('RATED|Rated', case=False) == False]

zomato

,name,online_order,book_table,rating,votes,location,rest_type,dish_liked,cuisines,approx_cost,type
0,Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet
4,Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet
...,...,...,...,...,...,...,...,...,...,...,...
56244,The Farm House Bar n Grill,No,No,3.7 /5,34,Whitefield,"Casual Dining, Bar",NA,"North Indian, Continental",800,Pubs and bars
56246,Bhagini,No,No,2.5 /5,81,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars
56247,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,Whitefield,Bar,NA,Continental,"1,500",Pubs and bars
56250,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars
56251,The Nest - The Den Bengaluru,No,No,3.4 /5,13,"ITPL Main Road, Whitefield","Bar, Casual Dining",NA,"Finger Food, North Indian, Continental","1,500",Pubs and bars

**Task-7 Unlocking Zomato's Culinary Data**

Dive deep into Zomato's dataset to understand dining experiences. Transforming data into insights empowers diners and restaurants alike. Each detail paints a clearer picture of Zomato's culinary world, enhancing dining experiences. Join us on this journey toward culinary clarity and authenticity.

In [7]:
#Filtering and Cleaning Data.
# Filter rows to keep only those where the 'online_order' column contains either 'Yes' or 'No'
zomato = zomato[zomato['online_order'].str.contains('Yes|No') == True]

# Clean the 'rating' column
zomato['rating'].replace('NEW', 0, inplace=True)
zomato['rating'].replace('-', 0, inplace=True)
zomato['rating'].replace(to_replace='/5', value='', regex=True, inplace=True)

# Inspect the data
zomato

,name,online_order,book_table,rating,votes,location,rest_type,dish_liked,cuisines,approx_cost,type
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet
...,...,...,...,...,...,...,...,...,...,...,...
56244,The Farm House Bar n Grill,No,No,3.7,34,Whitefield,"Casual Dining, Bar",NA,"North Indian, Continental",800,Pubs and bars
56246,Bhagini,No,No,2.5,81,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars
56247,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6,27,Whitefield,Bar,NA,Continental,"1,500",Pubs and bars
56250,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars
56251,The Nest - The Den Bengaluru,No,No,3.4,13,"ITPL Main Road, Whitefield","Bar, Casual Dining",NA,"Finger Food, North Indian, Continental","1,500",Pubs and bars

**Task-8 Crafting the Zomato Masterpiece**

In our journey through Zomato's dataset, we've refined our data to perfection. Using regular expressions, we've cleaned restaurant names, preserving authenticity. Now saved as 'zomatocleaned.csv,' every entry reflects true dining essence. Our mission: to elevate how we explore and savor food.

In [8]:
# Data Cleaning and Exporting to CSV.

# Clean the 'name' column
zomato['name'] = zomato['name'].str.replace(r'[Ãx][^A-Za-z]+', '', regex=True)

# Export the cleaned DataFrame to a CSV file
zomato.to_csv('zomatocleaned.csv', index=False)

**Now we ready for the Analysis**